export const cardArray = [
  {
    id: 0,
    title: 'Первый товар',
    price: '170 ₽',
    adress: 'Казань, р-н Вахитовский',
    date: '10 июля 11:39',
    img: '/images/card-img.png',
    description: 'Продаю не спеша самокат в хорошем состоянии.',
  },
  {
    id: 1,
    title: 'Второй товар',
    price: '171 ₽',
    adress: 'Казань, р-н Вахитовский',
    date: '10 июля 11:39',
    img: '/images/card-img.png',
    description: 'Продаю не спеша самокат в хорошем состоянии.',
  },
  {
    id: 2,
    title: 'Второй товар',
    price: '172 ₽',
    adress: 'Казань, р-н Вахитовский',
    date: '10 июля 11:39',
    img: '/images/card-img.png',
    description: 'Продаю не спеша самокат в хорошем состоянии.',
  },
  {
    id: 3,
    title: 'Второй товар',
    price: '173 ₽',
    adress: 'Казань, р-н Вахитовский',
    date: '10 июля 11:39',
    img: '/images/card-img.png',
    description: 'Продаю не спеша самокат в хорошем состоянии.',
  },
  {
    id: 4,
    title: 'Второй товар',
    price: '174 ₽',
    adress: 'Казань, р-н Вахитовский',
    date: '10 июля 11:39',
    img: '/images/card-img.png',
    description: 'Продаю не спеша самокат в хорошем состоянии.',
  },
  {
    id: 5,
    title: 'Второй товар',
    price: '175 ₽',
    adress: 'Казань, р-н Вахитовский',
    date: '10 июля 11:39',
    img: '/images/card-img.png',
    description: 'Продаю не спеша самокат в хорошем состоянии.',
  },
];
